repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8  # You can check for the latest version or use a specific version you need
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]  # Correctly specify file types

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
      entry: cmake-format
      types: [cmake]
