name: Build FlockMTL per Tag with Corresponding DuckDB

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma-separated tags to build (optional)'
        required: false
        default: ''

jobs:
  build-per-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: v0.3.1
            duckdb: v1.3.2
          - tag: v0.3.0
            duckdb: v1.3.2
          - tag: v0.2.5
            duckdb: v1.3.0
          - tag: v0.2.4
            duckdb: v1.1.3
          - tag: v0.2.3
            duckdb: v1.1.3
          - tag: v0.2.2
            duckdb: v1.1.3

    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@${{ matrix.duckdb }}
    with:
      duckdb_version: ${{ matrix.duckdb }}
      ci_tools_version: ${{ matrix.duckdb }}
      extension_name: flockmtl
      exclude_archs: 'wasm_mvp;wasm_threads;wasm_eh'
    secrets: inherit
